### ISSUE TITLE
Feature: Tutorial framework

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#1]
TODO: Fill out this issue stub

**Comment by lukasgolson** [comment]
It would be nice to make a extendable tutorial framework, where different tutorials can be selected from a tutorial book menu.

Tutorials should spawn players in an instanced location (similar to classrooms), and teach students about different features in the UBC MineTest Classroom.

Tutorials should initially include movement, MineTest features (punch a block), and chat. Framework should be easily expandable to include tutorials for Minetest Classroom features as well as individual mods.

Tutorials should reduce work load required for TA's and professors for teaching students how to use the platform. Might be expandable to include professor defined lesson modules.

**Comment by pauldpickell** [comment]
I like the idea of using the existing classrooms framework to spawn players into the tutorials. This would also allow us to distribute the game with these pre-built tutorial classrooms that would solve the issue of spawning directly into a singlenode mapgen.

**Comment by jocelynbachmann** [comment]
If using classrooms could overcomplicate things, these are some alternative options based on tutorials I've come across on other servers:

1. Use a building in the spawn location with different floors corresponding to different types of tutorials (e.g. floor 1 for basic controls, floor 2 for specific tools, etc.). Instructions would be on the walls or we could use a mob. This is the easiest option, and could work well given there's already a feature for returning the spawn location, so players could return to the tutorial at any time.

2. Use portals or travel boxes to transport to underground (or above ground) tutorial locations specific to the area the player is in. This would probably take a little more time or research, but there's worlds that use portals like this pretty extensively. There seem to be ways to limit who can access portals, which could be useful to restrict certain tutorials to teachers only or to control the pace at which students are uncovering new features. If not for tutorials, portals could still be an interesting mod to look into for teacher use (e.g. switching between groups of students/activities quickly, if this is time consuming using classrooms).

3. Access tutorials via the notebook menu which transport you to a specific tutorial area (or place you in a classroom). This is  probably the most intuitive option for players, but could be complicated and have limited scalability.

Options 2 and 3 potentially require an initial pop up when joining the server to explain how to do basic things like use the notebook or use a portal.

We've refactored the classroom system to make it easier to create worlds (which could be used to implement options 2 or 3). We're currently exploring each of the options.

**Comment by lukasgolson** [comment]
As an update; I've created and fleshed out a new realm system (as based on the classroom feature) to unify the creation of realms (worlds / classrooms / dimensions / etc.) and have integrated it into the mc_teacher classrooms feature. 

The realms system supplies simplified API to create large areas from schematics, to manage them, as well as to asynchronously clean them up when the area is no longer finished. It will also make managing players and entities within these areas easier as well.

Realms are 12 map-chunks by 12 map-chunks wide/long (960 nodes) and 4 map-chunks high (320 nodes) -- but this can be adjusted as necessary to accommodate current classroom map sizes. 

The system places realms along the X and Z axis (and eventually the Y axis as well) to increase the address space available for worlds.

Players start off in a realm that houses a spawn and our "punch-a-block" tutorial, navigation, and future tutorial frameworks. Each tutorial will be able to be instanced (i.e., each tutorial realm) and I am hoping to also get terrain generators working in the realms independent of world-type.

**Comment by pauldpickell** [comment]
> The realms system supplies simplified API to create large areas from schematics, to manage them, as well as to asynchronously clean them up when the area is no longer finished. It will also make managing players and entities within these areas easier as well.
> ...
> Players start off in a realm that houses a spawn and our "punch-a-block" tutorial, navigation, and future tutorial frameworks. Each tutorial will be able to be instanced (i.e., each tutorial realm) and I am hoping to also get terrain generators working in the realms independent of world-type.

Schematics was my approach as well, however, this requires some knowledge and patience using `WorldEdit` to create the schematics. For the lay user, I wonder if we could also add some preset mapgen options to generate classrooms with specific sizes/biomes and bounded by `unbreakable_map_barrier`? May also think about new classroom generation as a non-teacher privilege that can be granted to students, too, so that students can be assigned to their own spaces to build something or look at something. This could also facilitate group and project work. Perhaps integrating the `protector` mod would be useful here. 

> Realms are 12 map-chunks by 12 map-chunks wide/long (960 nodes) and 4 map-chunks high (320 nodes) -- but this can be adjusted as necessary to accommodate current classroom map sizes.

Seems reasonable. In testing, I found that the `VoxelManip` method is limited to ~ 7^3 map chunks. Need space between classrooms to avoid unnecessarily sending blocks from other classrooms and reduce lag.

> The system places realms along the X and Z axis (and eventually the Y axis as well) to increase the address space available for worlds.

The current address space is quite large, but I like the idea of being efficient with it. There is an upper limit to the number of simultaneous players on a server. With this in mind, probably a single large class or two small classes could simultaneously participate on the server.

**Comment by lukasgolson** [comment]
> Schematics was my approach as well, however, this requires some knowledge and patience using `WorldEdit` to create the schematics. For the lay user, I wonder if we could also add some preset mapgen options to generate classrooms with specific sizes/biomes and bounded by `unbreakable_map_barrier`? May also think about new classroom generation as a non-teacher privilege that can be granted to students, too, so that students can be assigned to their own spaces to build something or look at something. This could also facilitate group and project work. Perhaps integrating the `protector` mod would be useful here.

This gives me an idea for somehow integrating `minetest.create_schematic` to make it easier for the lay user to create areas that  can be consumed by the realm system. I'll also look into the schematic editor mod. The easier it is for creating realm templates for teachers, the better.

Variable realm size is something I'm interested in pursuing, but for now as we have so much space, I think generating within a realm without using up all its space would be sufficient. 

Mapgen options were also something I was thinking. I envision something where we could have a formspec page with options similar to those found on the world generation page of the main menu. I'll add in boundary generation for all realms. 

Finally, instanced realms assigned to each player or a group of players where they have their own spaces to work is a great feature that can come from this. I'll look into the protector mod for integration. This was the main reason for creating this system. We want players to have as much freedom to place / destroy blocks as possible during the tutorials.

> Seems reasonable. In testing, I found that the `VoxelManip` method is limited to ~ 7^3 map chunks. Need space between classrooms to avoid unnecessarily sending blocks from other classrooms and reduce lag.

The limit of the VoxelManip method had meant that I've had to step through the realms to modify them. Right now I'm queuing mapchunk modifications using ` minetest.emerge_area` which seems to prevent lag and crashes when working with massive areas, but I can probably optimize the way that it is working with the lua voxel manipulator.

I have a 2 mapchunk border surrounding the realm. It seems that each realm is still visible at the edges, I'll try to determine the render distance so that the realms/classrooms are properly isolated.

**Comment by pauldpickell** [comment]
Received the following debug output from server:
` WARNING[Main]: Undeclared global variable "portalwand" accessed at ...in/../games/Minetest_Classroom/mods/portals/init.lua:52`

and

`WARNING[Main]: Undeclared global variable "tutorialbook" accessed at ...st_Classroom-develop\mods\mc_tutorial_framework\init.lua:101`

and when "Go to UBC" button is clicked on teacher controller, the server crashes with debug output:

```
ACTION[Server]: singleplayer uses mc_teacher:controller, pointing at [nothing]
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback on_playerReceiveFields(): ...lop\mods\mc_worldmanager/realm/realmPlayerManagement.lua:15: bad argument #1 to 'pairs' (table expected, got nil)
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'pairs'
ERROR[Main]: 	...lop\mods\mc_worldmanager/realm/realmPlayerManagement.lua:15: in function 'RunTeleportInFunctions'
ERROR[Main]: 	...lop\mods\mc_worldmanager/realm/realmPlayerManagement.lua:3: in function 'TeleportPlayer'
ERROR[Main]: 	...\Minetest_Classroom-develop\mods\mc_teacher/gui_dash.lua:679: in function <...\Minetest_Classroom-develop\mods\mc_teacher/gui_dash.lua:663>
ERROR[Main]: 	...st\minetest-5.4.1-win64\bin\..\builtin\game\register.lua:422: in function <...st\minetest-5.4.1-win64\bin\..\builtin\game\register.lua:406>
```

**Comment by lukasgolson** [comment]
> and when "Go to UBC" button is clicked on teacher controller, the server crashes with debug output:

Fixed in #43

**Comment by pauldpickell** [comment]
@jocelynbachmann from [idea card](https://github.com/ubc-minetest-classroom/Minetest_Classroom/projects/1#card-82433384):

> Consider either refactoring tutorial book into notebook and controller tools, or including a separate section in the controller tool that explains portal creation (or add to realm management menu)

I think the basic tutorials need to be accessible from the `mc_teacher` and `mc_student` menus directly instead of a standalone tool. However, this exposes a related issue. As we start to consider adding tutorials that are specific to the spawn realm, we need to think about additional functionality that would allow someone else to set up their own server with tutorials. So for example, the user story might be something like this:

> I am a teacher who wants to be able to create my own sequence of tutorials and customize the trigger events so that I can tailor the tutorial content to my own custom spawn realm.

In other words, we do not want to be hard-coding trigger events based on our spawn realm for things like teleporting to the UBC bookstore, botanical garden, etc. Teachers should be able to either create a tutorial in a new realm or set the teleport position in their own spawn realm. I envision that the tutorials can really just be a special case of realms/classrooms that can be managed in the same way as realms (registered, created, destroyed), but are additionally defined by a progressive sequence and dependency. In this way, a teacher can basically set up their own tutorials, with their own schematics or map gen options, and those classroom/realms are automatically available to students. This would really extend the existing tutorial system beyond just punch-a-block and movement and instead allow us to define new tutorials for using the `magnify` tool at the botanical garden or moving to some location in the spawn realm in order to advance in the tutorial sequence. 

Could we create a "recording" tool that would allow a teacher player to basically register a series of event actions in their own game play that are needed to complete a given tutorial? For example something like:

> teacher uses mc_tutorial_framework:recorder, pointing at [nothing]
> --- Recording starts
> teacher digs default:dirt
> teacher digs default:dirt
> teacher digs default:dirt
> teacher uses mc_tutorial_framework:recorder, pointing at [nothing]
> --- Recording ends

Now that the trigger events are captured (the player has to dig 3 dirt), the teacher returns to a formspec to define what happens when the task is completed: unlock the next tutorial, give a tool, display a message, grant a privilege, etc. This framework would be highly extensible because it would be compatible with nearly any other mod. Below might be a sequence for finding 3 pine tree species in the botanical garden:

> teacher uses mc_tutorial_framework:recorder, pointing at [nothing]
> --- Recording starts
> teacher uses magnify:magnifying_tool, pointing at pine_trees:pinus_contorta
> teacher uses magnify:magnifying_tool, pointing at pine_trees:pinus_lambertiana
> teacher uses magnify:magnifying_tool, pointing at pine_trees:pinus_wallichiana
> teacher uses mc_tutorial_framework:recorder, pointing at [nothing]
> --- Recording ends

In this way, it would be super straightforward to add support for additional tools (e.g., `forestry-tools`) and nodes and allow a teacher to define a custom tutorial in any realm with their own schematic or mapgen.

**Comment by jocelynbachmann** [comment]
This sounds like a good idea, but I do think as we add more features to tutorials like levels, prizes, and teacher creation, it’s worth considering whether those additions make more sense as part of some kind of “activities” framework for creating activities/tasks for students. 

It could be that they’re better suited as part of tutorials, just thought I’d raise the idea since I think separating where tutorials can be found and expanding tutorials from just controls and tool use to more specific sequences of tasks could potentially get confusing for students/teachers, and raises the question of what separates a class activity/assignment from a tutorial. 

Regardless, it’s definitely important that we make sure the tutorial system isn’t specific to the UBC spawn realm, but I think another approach to consider could be that tutorials are kept as the small “external” realms we currently have them as and are used to simply explain the use of a tool and practice with it in a smaller context, but a teacher could add specialized activities in the spawn realm that allow students to practice using the tool in the specific context that’s needed for the lesson (or could enable a set of pre-made activities). 

Again, this could be more complicated than making everything tutorials, just thought I’d bring it up, even if only to clarify what else teachers might have students do in the game after completing tutorials.

**Comment by lukasgolson** [comment]
> This sounds like a good idea, but I do think as we add more features to tutorials like levels, prizes, and teacher creation, it’s worth considering whether those additions make more sense as part of some kind of “activities” framework for creating activities/tasks for students.
> 
> It could be that they’re better suited as part of tutorials, just thought I’d raise the idea since I think separating where tutorials can be found and expanding tutorials from just controls and tool use to more specific sequences of tasks could potentially get confusing for students/teachers, and raises the question of what separates a class activity/assignment from a tutorial.
> 
> Regardless, it’s definitely important that we make sure the tutorial system isn’t specific to the UBC spawn realm, but I think another approach to consider could be that tutorials are kept as the small “external” realms we currently have them as and are used to simply explain the use of a tool and practice with it in a smaller context, but a teacher could add specialized activities in the spawn realm that allow students to practice using the tool in the specific context that’s needed for the lesson (or could enable a set of pre-made activities).
> 
> Again, this could be more complicated than making everything tutorials, just thought I’d bring it up, even if only to clarify what else teachers might have students do in the game after completing tutorials.

One way this could be tied into UBC, however, is to have blocks/NPC's throughout the UBC map that teleport players to tutorial realms. Tutorial realms themselves could also contain parts of the UBC map via smaller schematics.

**Comment by pauldpickell** [comment]
Yes, that's a good point @jocelynbachmann and there is certainly some cross over with existing ideas such as the "manage task" function and the "manage lessons" placeholder in `mc_teacher`. Its possible that some "activities" or "lessons" framework could unify all of this, but it seems that this functionality would be best housed _within_ the tutorial system because the link with realm creation is already there and would be obvious to the teacher player.

My concern with the current approach to the tutorial system is that nearly everything is hard coded, which is specific to our leaves little room to dynamically update or add tutorials in the future. I agree that the proposed framework could get complicated, but I am not imagining that tutorials would be a replacement for all lesson-planning or classrooms that are lead by teacher instruction. Maybe that is how some teachers would use it, but as long as it works, it really should just add special sequence and dependency properties to the existing realm system. This also opens the possibility that anyone could create a tutorial about anything in Minetest, which would be incredibly useful. 

I do not think we need to over-complicate it for ourselves either. We really just need to check if a player's actions match the "recorded" key-values in a lua table and then provide the support to the teacher to define what happens next. I am sure others would extend this framework beyond whatever functionality we need for `Minetest_classroom`.

> One way this could be tied into UBC, however, is to have blocks/NPC's throughout the UBC map that teleport players to tutorial realms. Tutorial realms themselves could also contain parts of the UBC map via smaller schematics.

@lukasdragon Setting aside for a moment whether it is an external realm or the spawn realm (I think we could easily support both instances for tutorials), is this approach to tutorials feasible?

**Comment by pauldpickell** [comment]
Closing this since it is now superceded by #145
