### ISSUE TITLE
Compass HUD not displaying correctly in multiplayer mode

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#133]
**Describe the bug**
Title.

**To Reproduce**
1. Start multiplayer server.
2. Two players join the server.
3. Left-click to activate first sequence in compass HUD and it displays quickly then disappears. Cannot proceed to "unfold" the compass.
4. One player leaves the server and now the compass HUD element works again as expected.

**Expected behavior**
Should be able to left-click to see the closed compass, left-click again to see the "unfolded" compass. Then right-click to access the compass settings. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS

**Comment by Lowie375** [comment]
The fix for this is to refactor the compass so that variables like `open_HUD_showing`, `mag_declination`, `azimuth`, `curr_azimuth`, etc. are all tables indexed by player name instead of single variables. This does mean that you'll have to initialize variables for each player once they open the compass and add checks to see if variables exist when you need them, but that shouldn't be too difficult.

**Comment by jocelynbachmann** [comment]
Should be fixed in #146
