### ISSUE TITLE
Biomegen decorator produces mismatched decorations

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#148]
**Describe the bug**
Using the biomegen key for the decorator can create some weird results. Not sure if this is a bug of the biomegen mod or on our end, but I found some hybrid poplar-apple trees.

**To Reproduce**
1. `/realm new`
2. `/realm tp 2`
4. `/realm gen 2 v2 biomegen 10 123`
5. See result

**Expected behavior**
Should not see hybrid trees.

**Screenshots**
![image](https://user-images.githubusercontent.com/61996662/181655684-ed6be22b-58a3-4abf-85d4-84fc482626fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minetest: 5.5.1

**Comment by lukasgolson** [comment]
This looks like a bug in biomegen and how it has 3D height-based biomes. I'll fix this issue by setting biomes to be the same throughout each vertical slice of a realm.

**Comment by lukasgolson** [comment]
On further inspection, this does not look to be a bug with biomegen or our mod; or if it is, it is incredibly tough to debug.

 Rather I think it might be dependent on the specific schematic registered in the Minetest engine.  All other tree schematics appear to be working correctly, except this "hybrid" one. As soon as I started logging the name of each schematic when it is placed, this bug stopped occuring... Strange... I will keep digging.

**Comment by pauldpickell** [comment]
Fixed by #157

**Comment by lukasgolson** [comment]
Just looked into it briefly, this looks to be a known bug in biomegen. I’ll patch this on Monday.

On Jul 28, 2022, at 4:52 PM, pauldpickell ***@***.***> wrote:

﻿

Describe the bug
Using the biomegen key for the decorator can create some weird results. Not sure if this is a bug of the biomegen mod or on our end, but I found some hybrid poplar-apple trees.

To Reproduce
Steps to reproduce the behavior:

  1.  /realm new
  2.  /realm tp 2
  3.  /realm gen 2 v2 biomegen 10 123
  4.  See result

Expected behavior
Should not see hybrid trees.

Screenshots
[image]<https://user-images.githubusercontent.com/61996662/181655684-ed6be22b-58a3-4abf-85d4-84fc482626fc.png>

Desktop (please complete the following information):

  *   OS: Windows 10
  *   Minetest: 5.5.1
