### ISSUE TITLE
Realm specific player permissions

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#36]
From @pauldpickell comment on PR #32 

> This makes me think that we might need to dynamically issue privs (like 'fly') based on the realm. I can foresee teachers not wanting students to be flying around if the task is to dig or look at the ground. Through the Manage Students formspec, teachers can grant/revoke any priv, but we might want to change default privs on-join.

**Comment by pauldpickell** [comment]
There are some related functionalities to a basic validation to check that a player is allowed to be in the classroom realm (if not, return to spawn realm). Once, validated and permitted to be in the classroom:

1. Change the player's privileges to match the expectations for the realm ✓
2. Display an indefinite HUD text element that identifies to the player which realm they are in and possibly any corresponding information about the classroom (e.g., course code) ✓

3. All privs should still be able to be granted or revoked at any time by a teacher in the same realm as well as across the entire server world. Currently, `mc_teacher` has options to apply actions to: all; group; or selected. This needs to be updated so that: 
- A teacher can form groups only within non-spawn realms (i.e., other classrooms that they create); 
- A new "classroom" grouping needs to be added to the "apply action to" list that represents active players in that classroom realm at any instance; ✓
- The default "apply action to" is set to "classroom" when a teacher is in a classroom realm (to avoid a teacher accidentally applying an action to everyone on the server); ✓
- Access to classroom realms that are not tutorials needs to be restricted to students who are given a code or password to join the classroom. The old classroom system used a randomly generated number as an access code, but perhaps we can prompt the teacher to provide a code word on realm set-up in order to validate player spawning to the correct classroom realm. This also means access-restricted classroom realms cannot use a physical portal for teleporting.

**Comment by pauldpickell** [comment]
May also want to consider checking if the player has completed some sequence of initial tutorials to grant `shout` and `interact` privs before granting those privs on spawn in another realm.
