### ISSUE TITLE
Overhaul of Teacher Notebook UI/UX

### ISSUE THREAD

**Issue by pauldpickell** [ubc-minetest-classroom/Minetest_Classroom#55]
@lukasdragon Can you identify the main elements and functionality for the formspec UI?

**Comment by lukasgolson** [comment]
This covers all things I can think of (in no particular order) when creating new realms:

- Realm name (string input)
- Toggle whether realm should use a template or generator (bool input)
- Whether the realm is instanced for players, groups of players, or classrooms; or if the realm is non-instanced (same copy for all players)
- Whether the realm should be deleted when all players leave (bool input)
- Additional realm "mods" (groups of functions that will be able to be registered with the system and attached to realms; Currently supported and used by template loading but no infrastructure to register these mods yet)
- User permissions that students should have while in the realm (multiple select; or an array of checkboxes)


- Realm template (drop-down with all the schematics registered with the system)
**OR; if realm is generated**
- Realm size (numeric input)
- Generator type (drop-down)

**Comment by lukasgolson** [comment]
For realm management we need:

- [x] List of all current realms
When you select an item you can press buttons to:
- [x] Teleport to a realm
- [ ] Export realm to a schematic
- [x] Import schematic to realm
- [x] Delete realm (with confirmation)
- [x] If (you're in that realm, see your local position)
- [ ] Set realm spawn
- [x] See your local position

**Comment by mandyhuy** [comment]
To help me get a clearer picture of the system I need to design, please let me know if the system description I've begun to outline in [this Google doc](https://docs.google.com/document/d/1q2ugamsDCQ9ffboa-vSodoD5c18BKq8Vpzj2qJ5IWKo/edit?usp=sharing) is accurate (under titles "Terminology" and "Entity relationships"). Please feel free to make any comments directly on the doc, on Github, whatever is easiest. I will continue to update the doc to keep it accurate with the latest changes.  

I also have a few questions about @lukasdragon's above specifications, mostly due to my inexperience with Minetest:

**New realm creation**

- What does a realm using a **generator** v.s. a template mean?
- What kind of user permissions could students need in a realm?

**Realm management**

- Would a realm **map** or **list** be more suitable for our project?
- What is a **local position** within a realm? What does that look like?
- For “Set realm spawn,” do you mean setting a location where players are generated/start?

Furthermore, is there recorded somewhere concrete task examples of how Minetest may be used in the classroom, from all possible users (students, course managers etc.)? If not, I would like to pick some brains @pauldpickell, @lukasdragon, Michelle or Ginny to get a better idea of the pedagogical gap we're trying to fill.

**Comment by pauldpickell** [comment]
Teacher controller main menu:
- [x] Go to spawn realm
- [x] Remove Manage Lessons
- [x] Update Manage Classrooms to incorporate all the methods available for creating and managing realms as well as the terrain gen methods
- [x] Manage Classrooms
- [x] Manage Players (ensure this works)
- [x] Manger Server Rules (implement a simple way to update the text and an image for the server; refactor the `rules` mod)
- [x] Moderator

**Comment by pauldpickell** [comment]
Mostly solved by #231, #233, and #209. Outstanding items at this stage are captured by other issues.
